name: Compila y genera PDF

on:
    push:

jobs:
    compila:
        runs-on: ubuntu-latest

        steps:
          - name: Saludar
            uses: IsaiasRVH2/hello-world-action-by-isaiasrvh2@v1.0
            with:
              who_to_greet: Isaias
          - name: Checkout
            uses: actions/checkout@v4
          
          - name: Instalar .NET en el runner
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '9.0.x'

          - name: Instalar dependencias
            run: dotnet restore
          
          - name: Compilar
            run: dotnet build --no-restore

    crear-pdf:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
          - uses: baileyjm02/markdown-to-pdf@v1
            with:
              input_dir: docs
              output_dir: pdfs
              build_html: true
          - uses: actions/upload-artifact@v4
            with:
              name: docs
              path: pdfs
          
            
